name: pebble

services:
  
  db:
    image: postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pebble_admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: pebble_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources/postgres/initdb:/docker-entrypoint-initdb.d
volumes:
  postgres_data: